# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\workspace\UpSite\ui\UpSite_en.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_CTH(object):
    def setupUi(self, CTH):
        CTH.setObjectName(_fromUtf8("CTH"))
        CTH.resize(724, 643)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(CTH.sizePolicy().hasHeightForWidth())
        CTH.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/ICO/bug.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        CTH.setWindowIcon(icon)
        self.centralWidget = QtGui.QWidget(CTH)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.formLayout_2 = QtGui.QFormLayout(self.centralWidget)
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.tabWidget = QtGui.QTabWidget(self.centralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.baseTab = QtGui.QWidget()
        self.baseTab.setObjectName(_fromUtf8("baseTab"))
        self.gridLayout_8 = QtGui.QGridLayout(self.baseTab)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.widget_2 = QtGui.QWidget(self.baseTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        self.widget_2.setObjectName(_fromUtf8("widget_2"))
        self.verticalLayout = QtGui.QVBoxLayout(self.widget_2)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.basicParaWidget = QtGui.QWidget(self.widget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.basicParaWidget.sizePolicy().hasHeightForWidth())
        self.basicParaWidget.setSizePolicy(sizePolicy)
        self.basicParaWidget.setObjectName(_fromUtf8("basicParaWidget"))
        self.gridLayout = QtGui.QGridLayout(self.basicParaWidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.updatePara = QtGui.QPushButton(self.basicParaWidget)
        self.updatePara.setObjectName(_fromUtf8("updatePara"))
        self.gridLayout.addWidget(self.updatePara, 7, 1, 1, 1)
        self.label_7 = QtGui.QLabel(self.basicParaWidget)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout.addWidget(self.label_7, 0, 0, 1, 1)
        self.widget_7 = QtGui.QWidget(self.basicParaWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_7.sizePolicy().hasHeightForWidth())
        self.widget_7.setSizePolicy(sizePolicy)
        self.widget_7.setObjectName(_fromUtf8("widget_7"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.widget_7)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.num = QtGui.QLineEdit(self.widget_7)
        self.num.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.num.setObjectName(_fromUtf8("num"))
        self.horizontalLayout_2.addWidget(self.num)
        self.gridLayout.addWidget(self.widget_7, 0, 1, 1, 1)
        self.widget_6 = QtGui.QWidget(self.basicParaWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_6.sizePolicy().hasHeightForWidth())
        self.widget_6.setSizePolicy(sizePolicy)
        self.widget_6.setObjectName(_fromUtf8("widget_6"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.widget_6)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.name = QtGui.QLineEdit(self.widget_6)
        self.name.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly)
        self.name.setInputMask(_fromUtf8(""))
        self.name.setMaxLength(32767)
        self.name.setObjectName(_fromUtf8("name"))
        self.verticalLayout_6.addWidget(self.name)
        self.gridLayout.addWidget(self.widget_6, 2, 1, 1, 1)
        self.widget_8 = QtGui.QWidget(self.basicParaWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_8.sizePolicy().hasHeightForWidth())
        self.widget_8.setSizePolicy(sizePolicy)
        self.widget_8.setObjectName(_fromUtf8("widget_8"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.widget_8)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.alarmValue = QtGui.QLineEdit(self.widget_8)
        self.alarmValue.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.alarmValue.setObjectName(_fromUtf8("alarmValue"))
        self.horizontalLayout_3.addWidget(self.alarmValue)
        self.gridLayout.addWidget(self.widget_8, 5, 1, 1, 1)
        self.widget_4 = QtGui.QWidget(self.basicParaWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_4.sizePolicy().hasHeightForWidth())
        self.widget_4.setSizePolicy(sizePolicy)
        self.widget_4.setObjectName(_fromUtf8("widget_4"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.widget_4)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.recordTime = QtGui.QLineEdit(self.widget_4)
        self.recordTime.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.recordTime.setObjectName(_fromUtf8("recordTime"))
        self.verticalLayout_5.addWidget(self.recordTime)
        self.gridLayout.addWidget(self.widget_4, 3, 1, 1, 1)
        self.widget_10 = QtGui.QWidget(self.basicParaWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_10.sizePolicy().hasHeightForWidth())
        self.widget_10.setSizePolicy(sizePolicy)
        self.widget_10.setObjectName(_fromUtf8("widget_10"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.widget_10)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.handComboBox = QtGui.QComboBox(self.widget_10)
        self.handComboBox.setObjectName(_fromUtf8("handComboBox"))
        self.handComboBox.addItem(_fromUtf8(""))
        self.handComboBox.addItem(_fromUtf8(""))
        self.horizontalLayout_5.addWidget(self.handComboBox)
        self.gridLayout.addWidget(self.widget_10, 6, 1, 1, 1)
        self.widget_5 = QtGui.QWidget(self.basicParaWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_5.sizePolicy().hasHeightForWidth())
        self.widget_5.setSizePolicy(sizePolicy)
        self.widget_5.setObjectName(_fromUtf8("widget_5"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.widget_5)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.sampleInterval = QtGui.QLineEdit(self.widget_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sampleInterval.sizePolicy().hasHeightForWidth())
        self.sampleInterval.setSizePolicy(sizePolicy)
        self.sampleInterval.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.sampleInterval.setObjectName(_fromUtf8("sampleInterval"))
        self.horizontalLayout.addWidget(self.sampleInterval)
        self.sampleInvBox = QtGui.QComboBox(self.widget_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sampleInvBox.sizePolicy().hasHeightForWidth())
        self.sampleInvBox.setSizePolicy(sizePolicy)
        self.sampleInvBox.setObjectName(_fromUtf8("sampleInvBox"))
        self.sampleInvBox.addItem(_fromUtf8(""))
        self.sampleInvBox.addItem(_fromUtf8(""))
        self.sampleInvBox.addItem(_fromUtf8(""))
        self.horizontalLayout.addWidget(self.sampleInvBox)
        self.gridLayout.addWidget(self.widget_5, 4, 1, 1, 1)
        self.refreshPara = QtGui.QPushButton(self.basicParaWidget)
        self.refreshPara.setObjectName(_fromUtf8("refreshPara"))
        self.gridLayout.addWidget(self.refreshPara, 9, 1, 1, 1)
        self.calibrationClockButton = QtGui.QPushButton(self.basicParaWidget)
        self.calibrationClockButton.setObjectName(_fromUtf8("calibrationClockButton"))
        self.gridLayout.addWidget(self.calibrationClockButton, 8, 1, 1, 1)
        self.label_12 = QtGui.QLabel(self.basicParaWidget)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout.addWidget(self.label_12, 5, 0, 1, 1)
        self.label_14 = QtGui.QLabel(self.basicParaWidget)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout.addWidget(self.label_14, 6, 0, 1, 1)
        self.label_11 = QtGui.QLabel(self.basicParaWidget)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout.addWidget(self.label_11, 4, 0, 1, 1)
        self.label_10 = QtGui.QLabel(self.basicParaWidget)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout.addWidget(self.label_10, 3, 0, 1, 1)
        self.label_8 = QtGui.QLabel(self.basicParaWidget)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout.addWidget(self.label_8, 2, 0, 1, 1)
        self.stopRecord = QtGui.QPushButton(self.basicParaWidget)
        self.stopRecord.setObjectName(_fromUtf8("stopRecord"))
        self.gridLayout.addWidget(self.stopRecord, 10, 1, 1, 1)
        self.verticalLayout.addWidget(self.basicParaWidget)
        self.gridLayout_8.addWidget(self.widget_2, 0, 1, 2, 1)
        self.displayBasicInfoWidget = QtGui.QWidget(self.baseTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.displayBasicInfoWidget.sizePolicy().hasHeightForWidth())
        self.displayBasicInfoWidget.setSizePolicy(sizePolicy)
        self.displayBasicInfoWidget.setObjectName(_fromUtf8("displayBasicInfoWidget"))
        self.gridLayout_10 = QtGui.QGridLayout(self.displayBasicInfoWidget)
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.temperature_c = QtGui.QLCDNumber(self.displayBasicInfoWidget)
        self.temperature_c.setObjectName(_fromUtf8("temperature_c"))
        self.gridLayout_10.addWidget(self.temperature_c, 2, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.displayBasicInfoWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_10.addWidget(self.label_6, 3, 0, 1, 1)
        self.temperature_f = QtGui.QLCDNumber(self.displayBasicInfoWidget)
        self.temperature_f.setObjectName(_fromUtf8("temperature_f"))
        self.gridLayout_10.addWidget(self.temperature_f, 3, 1, 1, 1)
        self.co2concentration = QtGui.QLCDNumber(self.displayBasicInfoWidget)
        self.co2concentration.setObjectName(_fromUtf8("co2concentration"))
        self.gridLayout_10.addWidget(self.co2concentration, 0, 1, 1, 1)
        self.label_5 = QtGui.QLabel(self.displayBasicInfoWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_10.addWidget(self.label_5, 1, 0, 1, 1)
        self.humidity = QtGui.QLCDNumber(self.displayBasicInfoWidget)
        self.humidity.setObjectName(_fromUtf8("humidity"))
        self.gridLayout_10.addWidget(self.humidity, 1, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.displayBasicInfoWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_10.addWidget(self.label_4, 0, 0, 1, 1)
        self.label_9 = QtGui.QLabel(self.displayBasicInfoWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_10.addWidget(self.label_9, 2, 0, 1, 1)
        self.pressure = QtGui.QLCDNumber(self.displayBasicInfoWidget)
        self.pressure.setObjectName(_fromUtf8("pressure"))
        self.gridLayout_10.addWidget(self.pressure, 4, 1, 1, 1)
        self.label_13 = QtGui.QLabel(self.displayBasicInfoWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_13.setFont(font)
        self.label_13.setWordWrap(True)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_10.addWidget(self.label_13, 4, 0, 1, 1)
        self.gridLayout_8.addWidget(self.displayBasicInfoWidget, 0, 0, 2, 1)
        self.tabWidget.addTab(self.baseTab, _fromUtf8(""))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.gridLayout_3 = QtGui.QGridLayout(self.tab)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.deleteFileButton = QtGui.QPushButton(self.tab)
        self.deleteFileButton.setObjectName(_fromUtf8("deleteFileButton"))
        self.gridLayout_3.addWidget(self.deleteFileButton, 1, 1, 1, 1)
        self.refreshFiles = QtGui.QPushButton(self.tab)
        self.refreshFiles.setObjectName(_fromUtf8("refreshFiles"))
        self.gridLayout_3.addWidget(self.refreshFiles, 2, 1, 1, 1)
        self.receiveFiles = QtGui.QPushButton(self.tab)
        self.receiveFiles.setObjectName(_fromUtf8("receiveFiles"))
        self.gridLayout_3.addWidget(self.receiveFiles, 0, 1, 1, 1)
        self.fileOperTableWidget = QtGui.QTableWidget(self.tab)
        self.fileOperTableWidget.setObjectName(_fromUtf8("fileOperTableWidget"))
        self.fileOperTableWidget.setColumnCount(3)
        self.fileOperTableWidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.fileOperTableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.fileOperTableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.fileOperTableWidget.setHorizontalHeaderItem(2, item)
        self.gridLayout_3.addWidget(self.fileOperTableWidget, 0, 0, 7, 1)
        self.tranferFileButton = QtGui.QPushButton(self.tab)
        self.tranferFileButton.setObjectName(_fromUtf8("tranferFileButton"))
        self.gridLayout_3.addWidget(self.tranferFileButton, 3, 1, 1, 1)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.recordTab = QtGui.QWidget()
        self.recordTab.setObjectName(_fromUtf8("recordTab"))
        self.gridLayout_4 = QtGui.QGridLayout(self.recordTab)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.recordrangeBox = QtGui.QGroupBox(self.recordTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.recordrangeBox.sizePolicy().hasHeightForWidth())
        self.recordrangeBox.setSizePolicy(sizePolicy)
        self.recordrangeBox.setObjectName(_fromUtf8("recordrangeBox"))
        self.gridLayout_2 = QtGui.QGridLayout(self.recordrangeBox)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.queryButton = QtGui.QPushButton(self.recordrangeBox)
        self.queryButton.setObjectName(_fromUtf8("queryButton"))
        self.gridLayout_2.addWidget(self.queryButton, 7, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.recordrangeBox)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_2.addWidget(self.label_2, 1, 2, 1, 1)
        self.afterDateEdit = QtGui.QDateEdit(self.recordrangeBox)
        self.afterDateEdit.setObjectName(_fromUtf8("afterDateEdit"))
        self.gridLayout_2.addWidget(self.afterDateEdit, 6, 1, 1, 1)
        self.beginDateEdit = QtGui.QDateEdit(self.recordrangeBox)
        self.beginDateEdit.setDateTime(QtCore.QDateTime(QtCore.QDate(2001, 1, 1), QtCore.QTime(0, 0, 0)))
        self.beginDateEdit.setMaximumTime(QtCore.QTime(23, 59, 59))
        self.beginDateEdit.setObjectName(_fromUtf8("beginDateEdit"))
        self.gridLayout_2.addWidget(self.beginDateEdit, 5, 1, 1, 1)
        self.radioButton = QtGui.QRadioButton(self.recordrangeBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton.sizePolicy().hasHeightForWidth())
        self.radioButton.setSizePolicy(sizePolicy)
        self.radioButton.setObjectName(_fromUtf8("radioButton"))
        self.gridLayout_2.addWidget(self.radioButton, 5, 0, 1, 1)
        self.label = QtGui.QLabel(self.recordrangeBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_2.addWidget(self.label, 6, 0, 1, 1)
        self.alldateRadioButton = QtGui.QRadioButton(self.recordrangeBox)
        self.alldateRadioButton.setChecked(True)
        self.alldateRadioButton.setObjectName(_fromUtf8("alldateRadioButton"))
        self.gridLayout_2.addWidget(self.alldateRadioButton, 0, 0, 1, 1)
        self.beforedayRadioButton = QtGui.QRadioButton(self.recordrangeBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.beforedayRadioButton.sizePolicy().hasHeightForWidth())
        self.beforedayRadioButton.setSizePolicy(sizePolicy)
        self.beforedayRadioButton.setObjectName(_fromUtf8("beforedayRadioButton"))
        self.gridLayout_2.addWidget(self.beforedayRadioButton, 1, 0, 1, 1)
        self.beforeMonthRadioButton = QtGui.QRadioButton(self.recordrangeBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.beforeMonthRadioButton.sizePolicy().hasHeightForWidth())
        self.beforeMonthRadioButton.setSizePolicy(sizePolicy)
        self.beforeMonthRadioButton.setObjectName(_fromUtf8("beforeMonthRadioButton"))
        self.gridLayout_2.addWidget(self.beforeMonthRadioButton, 3, 0, 1, 1)
        self.beforeMonthBox = QtGui.QSpinBox(self.recordrangeBox)
        self.beforeMonthBox.setObjectName(_fromUtf8("beforeMonthBox"))
        self.gridLayout_2.addWidget(self.beforeMonthBox, 3, 1, 1, 1)
        self.beforeDayBox = QtGui.QSpinBox(self.recordrangeBox)
        self.beforeDayBox.setObjectName(_fromUtf8("beforeDayBox"))
        self.gridLayout_2.addWidget(self.beforeDayBox, 1, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.recordrangeBox)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_2.addWidget(self.label_3, 3, 2, 1, 1)
        self.gridLayout_4.addWidget(self.recordrangeBox, 0, 0, 1, 1)
        self.widget_3 = QtGui.QWidget(self.recordTab)
        self.widget_3.setObjectName(_fromUtf8("widget_3"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.widget_3)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.displayDetailInfoTableWidget = QtGui.QTableWidget(self.widget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.displayDetailInfoTableWidget.sizePolicy().hasHeightForWidth())
        self.displayDetailInfoTableWidget.setSizePolicy(sizePolicy)
        self.displayDetailInfoTableWidget.setObjectName(_fromUtf8("displayDetailInfoTableWidget"))
        self.displayDetailInfoTableWidget.setColumnCount(6)
        self.displayDetailInfoTableWidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.displayDetailInfoTableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.displayDetailInfoTableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.displayDetailInfoTableWidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.displayDetailInfoTableWidget.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.displayDetailInfoTableWidget.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.displayDetailInfoTableWidget.setHorizontalHeaderItem(5, item)
        self.verticalLayout_2.addWidget(self.displayDetailInfoTableWidget)
        self.gridLayout_4.addWidget(self.widget_3, 0, 1, 1, 1)
        self.fileOperWidget = QtGui.QWidget(self.recordTab)
        self.fileOperWidget.setObjectName(_fromUtf8("fileOperWidget"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.fileOperWidget)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.fileOperBox = QtGui.QGroupBox(self.fileOperWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fileOperBox.sizePolicy().hasHeightForWidth())
        self.fileOperBox.setSizePolicy(sizePolicy)
        self.fileOperBox.setObjectName(_fromUtf8("fileOperBox"))
        self.gridLayout_6 = QtGui.QGridLayout(self.fileOperBox)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.dirTreeView = QtGui.QTreeView(self.fileOperBox)
        self.dirTreeView.setObjectName(_fromUtf8("dirTreeView"))
        self.gridLayout_6.addWidget(self.dirTreeView, 0, 0, 1, 2)
        self.loadinFileButton = QtGui.QPushButton(self.fileOperBox)
        self.loadinFileButton.setObjectName(_fromUtf8("loadinFileButton"))
        self.gridLayout_6.addWidget(self.loadinFileButton, 1, 1, 1, 1)
        self.verticalLayout_4.addWidget(self.fileOperBox)
        self.gridLayout_4.addWidget(self.fileOperWidget, 2, 0, 1, 1)
        self.drawCurveWidget = QtGui.QWidget(self.recordTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.drawCurveWidget.sizePolicy().hasHeightForWidth())
        self.drawCurveWidget.setSizePolicy(sizePolicy)
        self.drawCurveWidget.setObjectName(_fromUtf8("drawCurveWidget"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.drawCurveWidget)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.drawCurveLayout = QtGui.QVBoxLayout()
        self.drawCurveLayout.setObjectName(_fromUtf8("drawCurveLayout"))
        self.horizontalLayout_6.addLayout(self.drawCurveLayout)
        self.gridLayout_4.addWidget(self.drawCurveWidget, 1, 1, 2, 1)
        self.groupBox = QtGui.QGroupBox(self.recordTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout_5 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.tempCheckBox = QtGui.QCheckBox(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tempCheckBox.sizePolicy().hasHeightForWidth())
        self.tempCheckBox.setSizePolicy(sizePolicy)
        self.tempCheckBox.setChecked(True)
        self.tempCheckBox.setObjectName(_fromUtf8("tempCheckBox"))
        self.gridLayout_5.addWidget(self.tempCheckBox, 3, 0, 1, 1)
        self.co2CheckBox = QtGui.QCheckBox(self.groupBox)
        self.co2CheckBox.setChecked(True)
        self.co2CheckBox.setObjectName(_fromUtf8("co2CheckBox"))
        self.gridLayout_5.addWidget(self.co2CheckBox, 0, 0, 1, 1)
        self.humiCheckBox = QtGui.QCheckBox(self.groupBox)
        self.humiCheckBox.setChecked(True)
        self.humiCheckBox.setObjectName(_fromUtf8("humiCheckBox"))
        self.gridLayout_5.addWidget(self.humiCheckBox, 4, 0, 1, 1)
        self.co2Line = QtGui.QLabel(self.groupBox)
        self.co2Line.setText(_fromUtf8(""))
        self.co2Line.setObjectName(_fromUtf8("co2Line"))
        self.gridLayout_5.addWidget(self.co2Line, 0, 1, 1, 1)
        self.tempLine = QtGui.QLabel(self.groupBox)
        self.tempLine.setText(_fromUtf8(""))
        self.tempLine.setObjectName(_fromUtf8("tempLine"))
        self.gridLayout_5.addWidget(self.tempLine, 3, 1, 1, 1)
        self.humLine = QtGui.QLabel(self.groupBox)
        self.humLine.setText(_fromUtf8(""))
        self.humLine.setObjectName(_fromUtf8("humLine"))
        self.gridLayout_5.addWidget(self.humLine, 4, 1, 1, 1)
        self.atmospheriCheckBox = QtGui.QCheckBox(self.groupBox)
        self.atmospheriCheckBox.setChecked(True)
        self.atmospheriCheckBox.setObjectName(_fromUtf8("atmospheriCheckBox"))
        self.gridLayout_5.addWidget(self.atmospheriCheckBox, 5, 0, 1, 1)
        self.batteryCheckBox = QtGui.QCheckBox(self.groupBox)
        self.batteryCheckBox.setChecked(True)
        self.batteryCheckBox.setObjectName(_fromUtf8("batteryCheckBox"))
        self.gridLayout_5.addWidget(self.batteryCheckBox, 6, 0, 1, 1)
        self.atmoLine = QtGui.QLabel(self.groupBox)
        self.atmoLine.setText(_fromUtf8(""))
        self.atmoLine.setObjectName(_fromUtf8("atmoLine"))
        self.gridLayout_5.addWidget(self.atmoLine, 5, 1, 1, 1)
        self.battLine = QtGui.QLabel(self.groupBox)
        self.battLine.setText(_fromUtf8(""))
        self.battLine.setObjectName(_fromUtf8("battLine"))
        self.gridLayout_5.addWidget(self.battLine, 6, 1, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox, 1, 0, 1, 1)
        self.tabWidget.addTab(self.recordTab, _fromUtf8(""))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.tabWidget)
        CTH.setCentralWidget(self.centralWidget)
        self.statusBar = QtGui.QStatusBar(CTH)
        self.statusBar.setToolTip(_fromUtf8(""))
        self.statusBar.setStatusTip(_fromUtf8(""))
        self.statusBar.setAutoFillBackground(True)
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        CTH.setStatusBar(self.statusBar)
        self.menuBar = QtGui.QMenuBar(CTH)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 724, 23))
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        self.fileMenu = QtGui.QMenu(self.menuBar)
        self.fileMenu.setObjectName(_fromUtf8("fileMenu"))
        self.helpMenu = QtGui.QMenu(self.menuBar)
        self.helpMenu.setObjectName(_fromUtf8("helpMenu"))
        CTH.setMenuBar(self.menuBar)
        self.openAct = QtGui.QAction(CTH)
        self.openAct.setObjectName(_fromUtf8("openAct"))
        self.loadAct = QtGui.QAction(CTH)
        self.loadAct.setObjectName(_fromUtf8("loadAct"))
        self.exitAct = QtGui.QAction(CTH)
        self.exitAct.setObjectName(_fromUtf8("exitAct"))
        self.action_4 = QtGui.QAction(CTH)
        self.action_4.setObjectName(_fromUtf8("action_4"))
        self.setparaAct = QtGui.QAction(CTH)
        self.setparaAct.setObjectName(_fromUtf8("setparaAct"))
        self.refreshAct = QtGui.QAction(CTH)
        self.refreshAct.setObjectName(_fromUtf8("refreshAct"))
        self.lookpicAct = QtGui.QAction(CTH)
        self.lookpicAct.setObjectName(_fromUtf8("lookpicAct"))
        self.helpAct = QtGui.QAction(CTH)
        self.helpAct.setObjectName(_fromUtf8("helpAct"))
        self.aboutAct = QtGui.QAction(CTH)
        self.aboutAct.setObjectName(_fromUtf8("aboutAct"))
        self.actionSave = QtGui.QAction(CTH)
        self.actionSave.setCheckable(False)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/image/16x16/save.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSave.setIcon(icon1)
        self.actionSave.setObjectName(_fromUtf8("actionSave"))
        self.actionHelp = QtGui.QAction(CTH)
        self.actionHelp.setCheckable(False)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/image/16x16/info.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionHelp.setIcon(icon2)
        self.actionHelp.setObjectName(_fromUtf8("actionHelp"))
        self.actionExit = QtGui.QAction(CTH)
        self.actionExit.setCheckable(False)
        self.actionExit.setChecked(False)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/image/16x16/close-tab.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExit.setIcon(icon3)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.actionRefresh = QtGui.QAction(CTH)
        self.actionRefresh.setCheckable(False)
        self.actionRefresh.setChecked(False)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/image/16x16/refresh.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRefresh.setIcon(icon4)
        self.actionRefresh.setObjectName(_fromUtf8("actionRefresh"))
        self.actionOpen = QtGui.QAction(CTH)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/image/16x16/folder.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpen.setIcon(icon5)
        self.actionOpen.setObjectName(_fromUtf8("actionOpen"))
        self.fileMenu.addAction(self.exitAct)
        self.helpMenu.addAction(self.helpAct)
        self.menuBar.addAction(self.fileMenu.menuAction())
        self.menuBar.addAction(self.helpMenu.menuAction())

        self.retranslateUi(CTH)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.exitAct, QtCore.SIGNAL(_fromUtf8("triggered()")), CTH.close)
        QtCore.QMetaObject.connectSlotsByName(CTH)

    def retranslateUi(self, CTH):
        CTH.setWindowTitle(_translate("CTH", "CTH", None))
        self.updatePara.setText(_translate("CTH", "Update Parameter", None))
        self.label_7.setText(_translate("CTH", "Device Num", None))
        self.handComboBox.setItemText(0, _translate("CTH", "Immediately", None))
        self.handComboBox.setItemText(1, _translate("CTH", "Manual", None))
        self.sampleInvBox.setItemText(0, _translate("CTH", "S", None))
        self.sampleInvBox.setItemText(1, _translate("CTH", "M", None))
        self.sampleInvBox.setItemText(2, _translate("CTH", "H", None))
        self.refreshPara.setText(_translate("CTH", "Refresh", None))
        self.calibrationClockButton.setText(_translate("CTH", "Clock", None))
        self.label_12.setText(_translate("CTH", "Alarm Value", None))
        self.label_14.setText(_translate("CTH", "Immediately/manual", None))
        self.label_11.setText(_translate("CTH", "Interval", None))
        self.label_10.setText(_translate("CTH", "Record Times", None))
        self.label_8.setText(_translate("CTH", "Measure Name", None))
        self.stopRecord.setText(_translate("CTH", "Stop Record", None))
        self.label_6.setText(_translate("CTH", "Temperature(℉)", None))
        self.label_5.setText(_translate("CTH", "Humidity(%)", None))
        self.label_4.setText(_translate("CTH", "CO2(PPM)", None))
        self.label_9.setText(_translate("CTH", "Temperature(℃)", None))
        self.label_13.setText(_translate("CTH", "Atmospheric  Pressure(hPa)", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.baseTab), _translate("CTH", "Basic Information", None))
        self.deleteFileButton.setText(_translate("CTH", "Delete File", None))
        self.refreshFiles.setText(_translate("CTH", "Refresh", None))
        self.receiveFiles.setText(_translate("CTH", "Receive File", None))
        item = self.fileOperTableWidget.horizontalHeaderItem(0)
        item.setText(_translate("CTH", "File Name", None))
        item = self.fileOperTableWidget.horizontalHeaderItem(1)
        item.setText(_translate("CTH", "File Size", None))
        item = self.fileOperTableWidget.horizontalHeaderItem(2)
        item.setText(_translate("CTH", "Update Time", None))
        self.tranferFileButton.setText(_translate("CTH", "Translate File", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("CTH", "File Operation", None))
        self.recordrangeBox.setTitle(_translate("CTH", "Record Quary Range", None))
        self.queryButton.setText(_translate("CTH", "Query", None))
        self.label_2.setText(_translate("CTH", "Days", None))
        self.radioButton.setText(_translate("CTH", "From", None))
        self.label.setText(_translate("CTH", "   To", None))
        self.alldateRadioButton.setText(_translate("CTH", "All Date", None))
        self.beforedayRadioButton.setText(_translate("CTH", "Before", None))
        self.beforeMonthRadioButton.setText(_translate("CTH", "Before", None))
        self.label_3.setText(_translate("CTH", "Months", None))
        item = self.displayDetailInfoTableWidget.horizontalHeaderItem(0)
        item.setText(_translate("CTH", "Time", None))
        item = self.displayDetailInfoTableWidget.horizontalHeaderItem(1)
        item.setText(_translate("CTH", "CO2", None))
        item = self.displayDetailInfoTableWidget.horizontalHeaderItem(2)
        item.setText(_translate("CTH", "Temperature", None))
        item = self.displayDetailInfoTableWidget.horizontalHeaderItem(3)
        item.setText(_translate("CTH", "Humidity", None))
        item = self.displayDetailInfoTableWidget.horizontalHeaderItem(4)
        item.setText(_translate("CTH", "Atmospheric Pressure", None))
        item = self.displayDetailInfoTableWidget.horizontalHeaderItem(5)
        item.setText(_translate("CTH", "Battery Voltage", None))
        self.fileOperBox.setTitle(_translate("CTH", "File Management", None))
        self.loadinFileButton.setText(_translate("CTH", "Load File", None))
        self.groupBox.setTitle(_translate("CTH", "Curve", None))
        self.tempCheckBox.setText(_translate("CTH", "Temperature", None))
        self.co2CheckBox.setText(_translate("CTH", "CO2", None))
        self.humiCheckBox.setText(_translate("CTH", "Humidity", None))
        self.atmospheriCheckBox.setText(_translate("CTH", "Atmospheric", None))
        self.batteryCheckBox.setText(_translate("CTH", "Battery", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.recordTab), _translate("CTH", "Record Query", None))
        self.fileMenu.setTitle(_translate("CTH", "File", None))
        self.helpMenu.setTitle(_translate("CTH", "Help", None))
        self.openAct.setText(_translate("CTH", "打开", None))
        self.loadAct.setText(_translate("CTH", "导入", None))
        self.exitAct.setText(_translate("CTH", "Exit", None))
        self.action_4.setText(_translate("CTH", "读取参数", None))
        self.setparaAct.setText(_translate("CTH", "设置参数", None))
        self.refreshAct.setText(_translate("CTH", "刷新", None))
        self.lookpicAct.setText(_translate("CTH", "查看曲线图", None))
        self.helpAct.setText(_translate("CTH", "Operation Information", None))
        self.aboutAct.setText(_translate("CTH", "About", None))
        self.actionSave.setText(_translate("CTH", "save", None))
        self.actionSave.setToolTip(_translate("CTH", "save", None))
        self.actionHelp.setText(_translate("CTH", "help", None))
        self.actionHelp.setToolTip(_translate("CTH", "help", None))
        self.actionExit.setText(_translate("CTH", "exit", None))
        self.actionExit.setToolTip(_translate("CTH", "exit", None))
        self.actionRefresh.setText(_translate("CTH", "refresh", None))
        self.actionRefresh.setToolTip(_translate("CTH", "refresh", None))
        self.actionOpen.setText(_translate("CTH", "open", None))
        self.actionOpen.setToolTip(_translate("CTH", "open", None))

import UpSite_rc

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    CTH = QtGui.QMainWindow()
    ui = Ui_CTH()
    ui.setupUi(CTH)
    CTH.show()
    sys.exit(app.exec_())

